### ISSUE TITLE
Unable to do anything

### ISSUE THREAD

**Issue by irskep** [jtushman/pivotal_tools#1]
I apologize for how non-specific this issue is.

I set $PIVOTAL_TOKEN and confirmed that it's correct. But none of the commands work - `show_stories` always returns `None`, and `add_story` gives me a traceback with HTTP 400 (bad request).

Perhaps the solution is better error handling for bad tokens?

**Comment by jtushman** [comment]
what OS are you on?  from a command line if you run `env | grep 'PIVOTAL_TOKEN'`  what do you get.  X out some of the characters.  Should be something like:

PIVOTAL_TOKEN=XXXXXXXe4607fd107863b27cd2XXXXXX

I will also work on adding better token checking!

**Comment by jtushman** [comment]
I don't think its a bad token -- that causes me other issues.  I bet it has to do with making sure your account had api access enabled.

In your project settings do you have Allow API Access unchecked? 

![screen shot 2013-08-16 at 9 59 05 pm](https://f.cloud.github.com/assets/176888/979150/a0efd1e0-06e0-11e3-9395-1466aa9de437.png)

**Comment by jtushman** [comment]
I confirmed that this is the case -- so I am going to close this issue -- let me know if you run into any more issues
