### ISSUE TITLE
Doesn't work with projects that require HTTPS

### ISSUE THREAD

**Issue by irskep** [jtushman/pivotal_tools#2]
Hi, it's me again. The real problem from #1 is that we have our project set up to require access via HTTPS. `pivotal_tools` uses hard-coded HTTP urls.

I may or may not invest the time to write a patch and fix it. I'd imagine just replacing `http` with `https` would work, though ideally there'd be some kind of protocol variable in the URL format strings.

**Comment by irskep** [comment]
(We did test that disabling the HTTPS requirement fixes the issue.)

**Comment by jtushman** [comment]
Cool -- thanks for being on the forefront -- let me see if I can patch that up.  Also as a FYI -- i just added the feature to be able to change story states (see the readme)

**Comment by jtushman** [comment]
patched in version 0.11.0.  let me know if this does not resolve

**Comment by irskep** [comment]
NP, I love reducing reasons to have browser tabs open. I already have command aliases written to use with our project, so it'll be nice when those actually work. :-)

**Comment by irskep** [comment]
Works great, thanks!

**Comment by jtushman** [comment]
\o/  excellent!
