### ISSUE TITLE
Tasks are not displayed in show_story

### ISSUE THREAD

**Issue by wkoot** [jtushman/pivotal_tools#5]
Tasks related to a story are not displayed in show_story. It's also not possible to add, remove, edit, or mark them.

**Comment by jtushman** [comment]
I will add tasks to show_stories shortly.

add/remove/edit/mark  I'll queue up as an enhancement.  And happily would except a pull-request ;)

**Comment by jtushman** [comment]
added in 0.14 to list tasks in show story
